name: Build and Publish Containers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE: ozyviking/python-nginx
  REGISTRY: ghcr.io
  MAIN_NGINX: "mainline"
  MAIN_PYTHON: "3.11"
  MAIN_OS: "bookworm"

jobs:
  build:
    strategy:
      matrix:
        python: [3.11]
        nginx: [mainline]
        os: [bookworm]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: "Checkout Branch: ${{ github.ref_name }}"
        id: build_checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Make dockerfiles
        run: makedocker --python ${{ matrix.python }} --nginx ${{ matrix.nginx }} --os ${{ matrix.os }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{env.REGISTRY}}/${{env.IMAGE}}
          # generate Docker tags based on the following events/attributes
          tags: |
            latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: build/${{ matrix.nginx }}/${{ matrix.os }}/${{ matrix.python }}
          tags: |
            ${{ ((matrix.os == env.MAIN_OS)&&(matrix.nginx == env.MAIN_NGINX)&&(matrix.python == env.MAIN_PYTHON)) && matrix.python }}
            ${{ ((matrix.os == env.MAIN_OS)&&(matrix.nginx == env.MAIN_NGINX)&&(matrix.python == env.MAIN_PYTHON)) && matrix.os }}
            ${{ ((matrix.os == env.MAIN_OS)&&(matrix.nginx == env.MAIN_NGINX)&&(matrix.python == env.MAIN_PYTHON)) && matrix.nginx }}
            ${{ matrix.python }}-${{ matrix.nginx }}-${{ matrix.os }}
